// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Envios.Models;

public partial class DetalleEnvio
{
    public int Id { get; set; }

    public int IdEnvio { get; set; }

    public int IdProducto { get; set; }

    public int Cantidad { get; set; }

    public string Comentario { get; set; }

    public virtual Envio IdEnvioNavigation { get; set; }

    public virtual Producto IdProductoNavigation { get; set; }
}